### ISSUE TITLE
Cores das Legendas poderiam ser constantes? [Sugestão]

### ISSUE THREAD

**Issue by caiocmpaes** [nazareno/dinheiro-nas-eleicoes2016#1]
Nos gráficos de Campina Grande, o tipo de receita 'Recursos Próprios' é de cor azul. Porém para os gráficos de JP e RJ, como esse valor não é o mais significativo, ele toma posição posterior nas legendas e fica verde.

A pergunta é:
**Há como fixar os valores 'Tipo Receita' para todos os gráficos para que eles não mudem de ordem e, consequentemente, cor?**

Talvez, aconteça confusão quando o leitor assumir que os gráficos depois de Campina Grande continuarão com as mesmas cores.

**Comment by nazareno** [comment]
Concordo, Caio. Ainda não descobri como fazer isso na biblioteca que estou usando (`rcdimple`).

**Comment by nazareno** [comment]
Resolvido no app, e já enviado no html também.
